version: '3'

services:
  mongodb:
    image: mongo:4.1
    container_name: mongodb
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: gUBX0EJqB53WtImxJz3WDvuTaDspG3xe
      MONGO_INITDB_DATABASE: credit_cards